[build]
  command = "npm run build"
  publish = "dist"

# Production context: all deploys from the Production branch set in your site's
# deploy contexts will inherit these settings.
[context.prod-financePWA]
  command = "npm run build"
  publish = "dist"

# Specific branch context: all deploys from this specific branch will inherit
# these settings.
[context.prod-financePWA.environment]
  NODE_ENV = "production"

# The following redirect is intended for use with most SPAs that handle
# routing internally.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
